# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: lendhub
networks:
- id: 10143
  start_block: 15294605
  
  contracts:
  - name: nftlendhub
    address:
    - 0x2A0d4970cd6958dFb0d88F6536240277CC7c3a95
    handler: src/EventHandlers.ts
    events:
    - event: NFTListed(uint256 indexed loanId, address indexed nftOwner, address indexed nftAddress, uint256 nftId, uint256 loanAmount, uint256 interestRate, uint256 duration, address loanToken)
    - event: LoanFunded(uint256 indexed loanId,  uint256 loanAmount, address indexed lender, address indexed borrower) # <-- , address indexed borrower in new deploy contract
   
    - event: LoanClaimed(uint256 indexed loanId, address indexed borrower, uint256 indexed loanAmount)
    - event: LoanRepaid(uint256 indexed loanId, address indexed borrower, address indexed lender, uint256 loanAmount) # <--, address indexed lender in new deploy contract
    - event: NFTClaimedByLender(uint256 indexed loanId, address indexed lender, address indexed borrower)
    - event: NFTWithdrawn(uint256 indexed loanId, address indexed owner)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: RepaymentClaimed(uint256 indexed loanId, address indexed lender, uint256 indexed loanAmount)
    - event: LoanCancelled(uint256 indexed loanId, address indexed owner)
unordered_multichain_mode: true
